export const data = [
  {
    title: "Primary Care Physicians",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "Dentists",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "OBGYNs",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "Psychologists",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "Psychiatrists",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "Therapist-Counselors",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
  {
    title: "Urgent Care",
    options: [
      { id: Math.random(), title: "Atlanta, GA" },
      { id: Math.random(), title: "Austin, TX" },
      { id: Math.random(), title: "Baltimore, MD" },
      { id: Math.random(), title: "Boston, MA" },
      { id: Math.random(), title: "Chicago, IL" },
      { id: Math.random(), title: "Dallas, TX" },
      { id: Math.random(), title: "Denver, CO" },
      { id: Math.random(), title: "Detroit, MI" },
      { id: Math.random(), title: "Houston, TX" },
      { id: Math.random(), title: "Indianapolis, IN" },
      { id: Math.random(), title: "Las Vegas, NV" },
      { id: Math.random(), title: "Los Angeles, CA" },
      { id: Math.random(), title: "Miami, FL" },
      { id: Math.random(), title: "New York, NY" },
      { id: Math.random(), title: "Orlando, FL" },
      { id: Math.random(), title: "Philadelphia, PA" },
      { id: Math.random(), title: "Phoenix, AZ" },
      { id: Math.random(), title: "Pittsburgh, PA" },
      { id: Math.random(), title: "San Antonio, TX" },
      { id: Math.random(), title: "San Diego, CA" },
      { id: Math.random(), title: "San Francisco, CA" },
      { id: Math.random(), title: "San Jose, CA" },
      { id: Math.random(), title: "Seattle, WA" },
      { id: Math.random(), title: "Tampa, FL" },
      { id: Math.random(), title: "Washington, DC" },
    ],
  },
];

export const more = [
  {
    title: "More",
    options: [
      { id: Math.random(), title: "Psychiatrist" },
      { id: Math.random(), title: "Ear, Nose & Throat Doctor" },
      { id: Math.random(), title: "Podiatrist" },
      { id: Math.random(), title: "Urologist" },
      { id: Math.random(), title: "Gastroenterologist" },
      { id: Math.random(), title: "Cardiologist" },
      { id: Math.random(), title: "Neurologist" },
      { id: Math.random(), title: "Orthopedic Surgeon" },
      { id: Math.random(), title: "Ophthalmologist" },
      { id: Math.random(), title: "Pediatrician" },
      { id: Math.random(), title: "Optometrist" },
      { id: Math.random(), title: "Eye Doctor" },
      { id: Math.random(), title: "Therapist Counselor" },
      { id: Math.random(), title: "Physical Therapist" },
      { id: Math.random(), title: "Psychologist" },
      { id: Math.random(), title: "View all" },
    ],
  },
];

export const more1 = [
  {
    title: "More",
    options: [
      { id: Math.random(), title: "Blue Cross Blue Shield Dental" },
      { id: Math.random(), title: "Cigna" },
      { id: Math.random(), title: "Cigna Dental" },
      { id: Math.random(), title: "Delta Dental" },
      { id: Math.random(), title: "Florida Blue Cross Blue Shield" },
      { id: Math.random(), title: "Humana Dental" },
      { id: Math.random(), title: "Humana" },
      { id: Math.random(), title: "Kaiser Permanente" },
      { id: Math.random(), title: "Metlife" },
      { id: Math.random(), title: "Multiplan PHCS" },
      { id: Math.random(), title: "UnitedHealthcare" },
      { id: Math.random(), title: "UnitedHealthcare Dental" },
      { id: Math.random(), title: "UnitedHealthcare Oxford" },
      { id: Math.random(), title: "1199SEIU" },
      { id: Math.random(), title: "View all" },
    ],
  },
];
